{
  "name": "CouchDB",
  "version": "1.0.0",
  "slug": "couchdb",
  "description": "Addon to run CouchDB in Home Assistant on Raspberry Pi",
  "arch": ["armhf", "armv7", "aarch64"],
  "startup": "before",
  "boot": "auto",
  "options": {},
  "schema": {},
  "panel_icon": "mdi:database",
  "requirements": [],
  "supported_protocols": ["websocket", "http", "https"],
  "documentation": "https://github.com/votre-utilisateur/homeassistant-addon-couchdb/blob/main/README.md",
  "ports": {
    "5984/tcp": "CouchDB HTTP port",
    "4369/tcp": "CouchDB port mapper daemon",
    "9100/tcp": "CouchDB clustering",
    "9101/tcp": "CouchDB clustering",
    "9102/tcp": "CouchDB clustering",
    "9103/tcp": "CouchDB clustering",
    "9104/tcp": "CouchDB clustering"
  }
}
